/** The key will be the index in the connections array which will hold the
 * linked list*/
const squaresMap = new Map()
// Not doing it with a for loop to know which index they represent in the array
squaresMap.set("0", "a1")
squaresMap.set("1", "a2")
squaresMap.set("2", "a3")
squaresMap.set("3", "a4")
squaresMap.set("4", "a5")
squaresMap.set("5", "a6")
squaresMap.set("6", "a7")
squaresMap.set("7", "a8")
// B
squaresMap.set("8", "b1")
squaresMap.set("9", "b2")
squaresMap.set("10", "b3")
squaresMap.set("11", "b4")
squaresMap.set("12", "b5")
squaresMap.set("13", "b6")
squaresMap.set("14", "b7")
squaresMap.set("15", "b8")
// C
squaresMap.set("16", "c1")
squaresMap.set("17", "c2")
squaresMap.set("18", "c3")
squaresMap.set("19", "c4")
squaresMap.set("20", "c5")
squaresMap.set("21", "c6")
squaresMap.set("22", "c7")
squaresMap.set("23", "c8")
// D
squaresMap.set("24", "d1")
squaresMap.set("25", "d2")
squaresMap.set("26", "d3")
squaresMap.set("27", "d4")
squaresMap.set("28", "d5")
squaresMap.set("29", "d6")
squaresMap.set("30", "d7")
squaresMap.set("31", "d8")
// E
squaresMap.set("32", "e1")
squaresMap.set("33", "e2")
squaresMap.set("34", "e3")
squaresMap.set("35", "e4")
squaresMap.set("36", "e5")
squaresMap.set("37", "e6")
squaresMap.set("38", "e7")
squaresMap.set("39", "e8")
// F
squaresMap.set("40", "f1")
squaresMap.set("41", "f2")
squaresMap.set("42", "f3")
squaresMap.set("43", "f4")
squaresMap.set("44", "f5")
squaresMap.set("45", "f6")
squaresMap.set("46", "f7")
squaresMap.set("47", "f8")
//G
squaresMap.set("48", "g1")
squaresMap.set("49", "g2")
squaresMap.set("50", "g3")
squaresMap.set("51", "g4")
squaresMap.set("52", "g5")
squaresMap.set("53", "g6")
squaresMap.set("54", "g7")
squaresMap.set("55", "g8")
// H
squaresMap.set("56", "h1")
squaresMap.set("57", "h2")
squaresMap.set("58", "h3")
squaresMap.set("59", "h4")
squaresMap.set("60", "h5")
squaresMap.set("61", "h6")
squaresMap.set("62", "h7")
squaresMap.set("63", "h8")

export default squaresMap
